import type { LineItemTemplate } from "./types";

const stamp = "2026-01-01T00:00:00.000Z";

export const SEED_TEMPLATES: LineItemTemplate[] = [
  {
    id: "tpl-website",
    name: "Website Design & Development",
    title: "Website Design & Development",
    quantity: 1,
    unitPrice: 0,
    currency: "NGN",
    details: [
      "Discovery workshop and information architecture",
      "Custom responsive design (mobile, tablet, desktop)",
      "Development on an agreed modern stack",
      "Core pages and contact / lead capture flows",
      "Basic on-page SEO setup and performance pass",
      "Staging review, revisions round, and go-live support",
    ],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "tpl-seo",
    name: "SEO Package",
    title: "Search Engine Optimisation (SEO)",
    quantity: 1,
    unitPrice: 0,
    currency: "NGN",
    details: [
      "Technical SEO audit and priority fix list",
      "Keyword and intent research for target pages",
      "On-page optimisation (titles, meta, headings, internal links)",
      "Schema / structured data where relevant",
      "Monthly ranking and visibility reporting",
    ],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "tpl-retainer",
    name: "Monthly Retainer",
    title: "Ongoing Support Retainer",
    quantity: 1,
    unitPrice: 0,
    currency: "NGN",
    details: [
      "Agreed monthly hours for updates and improvements",
      "Website care, backups monitoring, and uptime checks",
      "Content and landing-page updates within scope",
      "Priority support via email / WhatsApp during business hours",
      "Monthly summary of work completed",
    ],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "tpl-digital-forge",
    name: "Digital Forge Product",
    title: "Digital Forge — Digital Product / System",
    quantity: 1,
    unitPrice: 0,
    currency: "NGN",
    details: [
      "Access to the agreed Digital Forge product or system",
      "Setup guidance and delivery assets",
      "Usage documentation where applicable",
      "Support window as stated in the offer",
    ],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "tpl-custom",
    name: "Custom Scope",
    title: "Custom Professional Services",
    quantity: 1,
    unitPrice: 0,
    currency: "NGN",
    details: [
      "Scope to be agreed in writing before work begins",
      "Deliverables listed below or in the attached brief",
      "Timeline and milestones confirmed after discovery",
    ],
    createdAt: stamp,
    updatedAt: stamp,
  },
];
